name: (Auto) Create issue for dependabot PR
on:
  pull_request:
    branches:
      - master
    types: [ opened, reopened]

jobs:
  dependency-issue:
    if: github.event.pull_request.user.login  == 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v4

      - name: Open Dependabot PR Issue
        env:
          pr_title: ${{github.event.pull_request.title}}
          pr_number: ${{github.event.pull_request.number}}
          pr_url: ${{github.event.pull_request.url}}
        run: |
          title="Dependabot PR $pr_title opened"
          body="Dependabot has opened PR #$pr_number\nLink: $pr_url"
          gh issue create --title "$title" --body "$body" --label "dependencies"
