name: .reusable release
on: push
jobs:
  semver:
    uses: ./.github/workflows/job.git-semver.yml
    secrets: inherit

  tag:
    if: ${{ !fromJSON(needs.semver.outputs.isTagged) }}
    needs:
      - semver
    uses:
      ./.github/workflows/job.create-tag.yml
    with:
      label: ${{ needs.semver.outputs.semver }}
      lightweight: true
      dryRun: ${{ (github.ref != 'refs/heads/master') }}
    secrets: inherit

  release:
    uses:
      ./.github/workflows/job.create-release.yml
    needs:
      - semver
      - tag
    with:
      version: ${{ needs.semver.outputs.semver }}
      dryRun: ${{ (github.ref != 'refs/heads/master') }}
    secrets: inherit
