name: .reusable release
on: push
jobs:
  gitlog:
    uses: ./.github/workflows/job.git-log.yml
    secrets: inherit

  release:
    uses:
      ./.github/workflows/job.release.yml
    needs:
      - gitlog
    with:
      version: ${{ needs.gitlog.outputs.semver }}
      createRelease: ${{ github.ref == 'refs/heads/master' }}
      createTag: ${{ !fromJSON(needs.gitlog.outputs.isTagged) }}
      lightweightTag: true
    secrets: inherit
