name: BuildService
on:
  workflow_call:
    outputs:
      moduleName:
        value: ${{ jobs.qa.outputs.moduleName }}
      ingressPath:
        value: ${{ jobs.qa.outputs.ingressPath }}
      serviceName:
        value: ${{ jobs.qa.outputs.serviceName }}
      gitVersion:
        value: ${{ jobs.qa.outputs.version }}
      goVersion:
        value: ${{ jobs.qa.outputs.goVersion }}

jobs:
  qa:
    uses: ./.github/workflows/module-qa.yml
    secrets: inherit
  
  build:
    name: 'build ${{ needs.qa.outputs.version }}'
    runs-on: ubuntu-latest
    needs:
    - qa
    outputs:
      gitVersion: ${{ needs.qa.outputs.version }}
      serviceName: ${{ needs.qa.outputs.serviceName }}
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: 'setup: docker buildx'
      uses: docker/setup-buildx-action@v3

    - name: 'docker: login'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'docker: metadata'
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ needs.qa.outputs.serviceName }}

    - name: 'docker: build and push'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: .cicd/dockerfile
        provenance: false # not currently supported by ghcr.io (creates spurious additional package versions)
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ needs.qa.outputs.serviceName }}:${{ needs.qa.outputs.version }}
        labels: ${{ steps.meta.outputs.labels }}

