name: 'job: snyk'
on:
  workflow_call:
permissions:
  contents: read         # required to checkout the repository
  security-events: write # required to upload SARIF results

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'snyk: scan'
        uses: snyk/actions/golang@0.4.0
        with:
          args: --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true # ensures we upload results

      - name: 'snyk: upload to Github/Code Scanning'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
