name: 'job: git log analysis'
on:
  workflow_call:
    outputs:
      # semver is an output that contains the version to be applied based on any current version and the
      # conventional commits in the git log
      semver:
        value: ${{ jobs.semver.outputs.semver }}
        description: 'The semantic version of the HEAD commit or the next version based on conventional commits since the most recent semver tag'
      # isTagged is an output that indicates whether the semver output represents an existing tag (true) or not (false)
      isTagged:
        value: ${{ jobs.semver.outputs.isTagged }}
        description: 'true if the semver output is an existing tag; false if the semver output is a new version, yet to be tagged'

jobs:
  semver:
    name: 'semantic version'
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.gitlog.outputs.semver }}
      isTagged: ${{ steps.gitlog.outputs.isTagged }}
    steps:
      - name: 'checkout'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # required to have a log to analyse

      - name: 'analyse log'
        id: gitlog
        shell: bash --noprofile --norc {0}
        run: |
          # script to identify the semantic version from conventional commits in the git log and preview the release change log

          echo "::notice::$(git version)"

          semver=""
          isTagged="false"

          tags=$(git tag --sort=-version:refname)
          if [[ -z "$tags" ]]; then
            # no tags => no previous tag; this is the initial release but we must
            # also check that the repo was cloned with a non-empty master branch

            echo "::warning::no tags found"

            if [[ ! -z $(git log origin/master..HEAD --oneline | grep "fatal:ambiguous argument 'origin/master..HEAD'") ]]; then
              echo "::warning::${{ github.ref }} not parented on 'master'; did you forget to clone a non-empty master branch when initialising this repo?"
            fi

            log=$(git log --oneline)
          else
            echo "::group::tags"
              echo "$tags"
            echo "::endgroup::"

            # get the most recent semver tag and the log since that tag

            tag=$(echo "$tags" | grep -m 1 -E "^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$")
            log=$(git log $tag..HEAD --oneline)
          fi

          echo "::group::log"
            echo "$log"
            [[ -n $tag ]] && echo ">> $tag"
          echo "::endgroup::"

          regex="^[v]{0,1}([0-9]+)\.([0-9]+)\.([0-9]+).*"
          major=0; minor=0; patch=0
          [[ $tag =~ $regex ]] && {
              major="${BASH_REMATCH[1]}"
              minor="${BASH_REMATCH[2]}"
              patch="${BASH_REMATCH[3]}"
          }

          if [[ ! -z $log ]]; then
            # determine the next semver based on any conventional commits in the log
            # --oneline log format is: xxxxxxx <commit type>[(<scope>)]: <message>
            
            badRefactorings=$(echo "log" | grep -E "^[0-9a-f]{7} (refactor!|refactor\(.*\)!): .+" -c)
            breaking=$(echo "$log"       | grep -E "^[0-9a-f]{7} (feat!|feat\(.*\)!|fix!|fix\(.*\)!): .+" -c)
            fixes=$(echo "$log"          | grep -E "^[0-9a-f]{7} (fix|fix\(.*\)): .+" -c)
            features=$(echo "$log"       | grep -E "^[0-9a-f]{7} (feat|feat\(.*\)): .+" -c)
            refactorings=$(echo "$log"   | grep -E "^[0-9a-f]{7} (refactor|refactor\(.*\)): .+" -c)

            echo "::group::conventional commits"
              echo "badRefactorings=$badRefactorings"
              echo "breaking=$breaking"
              echo "fixes=$fixes"
              echo "features=$features"
              echo "refactorings=$refactorings"
            echo "::endgroup::"

            if [[ $badRefactorings -gt 0 ]]; then
              echo "::error::refactoring commits cannot be breaking changes; rewrite with a more appropriate commit type (feat!/fix!)"
              exit 1
            fi
            #TODO: warn if there are any BREAKING CHANGE commits (recommend fix!/feature! as preferred)

            semver="?"
            if [[ -z $tag ]]; then
              if [[ ($breaking -gt 0) || ($features -gt 0) || ($fixes -gt 0) ]]; then
                # significant commits identified and there is no prior tag; this will be the
                # initial version (v0.1.0 by convention) regardless of the significance
                # of the commits
                major=0; minor=1; patch=0
              else
                # no significant commits found
                #
                # isTagged is set true to avoid running tests or releasing since (according to the
                # conventional commits in the log) there is not yet any functionality to be tested
                # or released
                [[ "$branch" != "master" ]] && {
                  echo "::warning::no significant commits; nothing to test/release"
                }
                isTagged="true"
              fi
            elif [[ $breaking -gt 0 ]]; then
              major=$((major+1))
              minor=0
              patch=0
            elif [[ $features -gt 0 ]]; then
              minor=$((minor+1))
              patch=0
            elif [[ $fixes -gt 0 || refactorings -gt 0 ]]; then
              patch=$((patch+1))
            else
              # no significant commits found but there is an existing release tag;
              # we assume that the commits are not code-related (documentation, ci/cd etc)
              # leaving the version unchanged and setting isTagged to true
              [[ "$branch" != "master" ]] && {
                echo "::warning::no significant commits since $tag; version unchanged; test/release will be skipped"
              }
              isTagged="true"
            fi
          fi
          [[ "$semver" == "?" ]] && semver="v$major.$minor.$patch"

          # if not master add a semver label identifying the branch
          # and emit an (approximate) preview of the release notes

          branch="${{ github.ref }}"
          branch=$(echo "$branch" | sed -E "s/refs\/heads\///")

          [[ "$branch" != "master" && $isTagged != "true" ]] && {
            semver+="-$branch"

            echo -e "### :ticket: $semver\n" >> $GITHUB_STEP_SUMMARY
            echo -e "> _:point_right: will be tagged as v$major.$minor.$patch when merged_\n" >> $GITHUB_STEP_SUMMARY
            project="https://github.com/${{ github.repository }}"
            changelog=""
            regex="^([0-9a-f]{7}) (.+)$"
            while read entry; do
              [[ ! $entry =~ $regex ]] && continue

              sha="${BASH_REMATCH[1]}"
              msg="${BASH_REMATCH[2]}"

              changelog+="[<code>$sha</code>]($project/commit/$sha) $msg\n"
            done <<< "$log"

            echo -e "### :clipboard: &nbsp;&nbsp; change log \n" >> $GITHUB_STEP_SUMMARY
            echo -e "$changelog\n" >> $GITHUB_STEP_SUMMARY
          }

          echo "semver=$semver" >> $GITHUB_OUTPUT
          echo "isTagged=$isTagged" >> $GITHUB_OUTPUT

          echo "::group::outputs"
            cat $GITHUB_OUTPUT
          echo "::endgroup::"
