name: 'job: release'
on:
  workflow_call:
    inputs:
      createRelease:
        description: 'whether to create a release (true) or not (false); typically set false when executing on a non-release branch'
        type: boolean
        required: true
      createTag:
        description: 'whether to create a tag for the release (true) or use the latest tag (false); ignored if createRelease is false'
        type: boolean
        required: true
      lightweightTag:
        description: 'whether to create a lightweight tag (true) or an annotated tag (false); ignored if createTag is false'
        type: boolean
        required: false
        default: false
      version:
        description: 'the version to be tagged (if required) and released'
        type: string
        required: true
      goVersion:
        description: 'the version of Go to use (only required if the release produces go binaries)'
        type: string
        required: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # check for presence of .goreleaser.yml
      - name: 'release: check configuration'
        id: config
        run: |
          # a script to check for the presence of a .goreleaser.yml file

          if [[ -f .goreleaser.yml ]]; then
            if [[ -z "$(cat .goreleaser.yml)" ]]; then
              echo "::error::.goreleaser.yml is empty"
              exit 1
            fi

            echo "found .goreleaser.yml:"
            awk '{print "| "$0}' .goreleaser.yml

            echo "GO_VERSION=$(go version)" >> $GITHUB_OUTPUT

            echo "::group::outputs"
              cat $GITHUB_OUTPUT
            echo "::endgroup::"            

            exit 0
          fi

          echo "::error::no .goreleaser.yml)"
          exit 1

      # create a tag
      - name: 'tag: create (annotated)'
        if: ${{ inputs.CreateRelease && inputs.createTag && !inputs.lightweightTag}}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ inputs.version }}
          message: |
            Release ${{ inputs.version }}
            https://github.com/${{ github.repository }}/releases/tag/${{ inputs.version }}

      - name: 'tag: create (lightweight)'
        if: ${{ inputs.CreateRelease && inputs.createTag && inputs.lightweightTag}}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ inputs.version }}

      # install Go and download dependencies
      - name: 'go: setup ${{ inputs.goVersion }}'
        if: ${{ inputs.createRelease && (inputs.goVersion != '') }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.goVersion }}
          cache: false   # avoid "file exists" errors from tar: https://github.com/actions/setup-go/issues/403
    
      - name: 'go: mod download'
        if: ${{ inputs.createRelease && (inputs.goVersion != '') }}
        run: go mod download

      # create the release
      - name: 'release: goreleaser'
        if: ${{ inputs.CreateRelease }}
        uses: goreleaser/goreleaser-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO_VERSION: ${{ steps.config.outputs.GO_VERSION }}
        with:
          args: release --clean ${{ steps.config.outputs.config }}
