name: ModulePipeline
on:
  workflow_call:
   
jobs:
  module-qa:
    uses: ./.github/workflows/module-qa.yml
    secrets: inherit

  release-tag:
    runs-on: ubuntu-latest
    needs:
      - module-qa
    steps:
      - name: checkout
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'github: create release v${{ needs.module-qa.outputs.version }}'
        if: ${{ (github.ref == 'refs/heads/master') && (needs.module-qa.outputs.isTagged == 'false') }}
        uses: ncipollo/release-action@v1
        with:
          commit: master
          tag: 'v${{ needs.module-qa.outputs.version }}'
          body: '${{ needs.module-qa.outputs.releaseComment }}'

      - name: 'github: release summary'
        run: |
          # script to add details of the release to the job summary
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            releaseLink="https://github.com/${{ github.repository }}/releases/edit/v${{ needs.module-qa.outputs.version }}"

            if [[ "${{ needs.module-qa.outputs.isTagged }}" == "true" ]]; then
              echo -e ":warning:&emsp;a release was not created\n" >> $GITHUB_STEP_SUMMARY
              echo -e "a tag for v${{ needs.module-qa.outputs.version }} already exists; [click here to edit the release]($releaseLink)(if one exists)\n" >> $GITHUB_STEP_SUMMARY
              exit 0
            fi

            releaseComment="${{ needs.module-qa.outputs.releaseComment }}"
            [[ -z $releaseComment ]] && releaseComment="_<no description>_"
            
            echo -e "### :octocat: v${{ needs.module-qa.outputs.version }} &nbsp;&nbsp; $releaseComment\n" >> $GITHUB_STEP_SUMMARY
            echo -e "\n---\n[_edit release_]($releaseLink)\n" >> $GITHUB_STEP_SUMMARY
            exit 0
          fi

          version="${{ needs.module-qa.outputs.version }}"
          releaseVersion="v${version%-*}"
          echo -e "### :crystal_ball: Release Preview\n> _the following release will be created when this branch is merged_\n" >> $GITHUB_STEP_SUMMARY
          echo -e "### $releaseVersion &nbsp;&nbsp; ${{ needs.module-qa.outputs.releaseComment }}\n" >> $GITHUB_STEP_SUMMARY
