name: pipeline.module-release
on:
  workflow_call:
   
jobs:
  module-qa:
    uses: ./.github/workflows/job.module-qa.yml
    secrets: inherit

  release:
    needs:
      - module-qa
    uses: ./.github/workflows/job.release.yml
    with:
      version: ${{ needs.module-qa.outputs.semver }}
      createRelease: ${{ (github.ref == 'refs/heads/master') }}
      createTag: ${{ !fromJSON(needs.module-qa.outputs.isTagged) }}
    secrets: inherit
