name: 'pipeline: module-release'
on:
  workflow_call:
jobs:
  qa:
    uses: ./.github/workflows/job.module-qa.yml
    secrets: inherit

  tag:
    if: ${{ !fromJSON(needs.qa.outputs.isTagged) }}
    uses: ./.github/workflows/job.create-tag.yml
    needs:
      - qa
    with:
      label: ${{ needs.qa.outputs.semver }}
      description: ${{ needs.qa.outputs.semver }}
      lightweight: ${{ !fromJSON(needs.qa.outputs.isTagged) }}
      dryRun: ${{ (github.ref != 'refs/heads/master') }}

  release:
    needs:
      - qa
      - tag
    uses: ./.github/workflows/job.create-release.yml
    with:
      version: ${{ needs.qa.outputs.semver }}
      goVersion: ${{ needs.qa.outputs.goVersion }}
      dryRun: ${{ (github.ref != 'refs/heads/master') }}
